<!DOCTYPE html>
<html>
<head>
<link href="static/css/ksi.css" type="text/css" rel="stylesheet">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Ξξ KSI</title>
</head>
<body>
  <div class="root diary">
    <h1>KSI - Jäsensivusto</h1>
    <div class="info-box name">Pekka Pilotti</div>
    <div class="tabs">
    <nav>
      <ul>
        <li><a href="index.html">Etusivu</a></li>
        <li><a href="index.html">Omat</a></li>
        <li><a href="index.html">Kalenterit</a></li>
        <li><a href="index.html">Lento <img src="static/img/down.png"></a>
            <ul>
                <li><a href="diary.html">Matkapäiväkirja</a></li>
            </ul>
        </li>
        <li><a href="index.html">Rekisterit <img src="static/img/down.png"></a></li>
        <li><a href="index.html">Tietopankki</a></li>
        <li><a href="index.html">Keskustelufoorumi</a></li>
        <li><a href="index.html">Ylläpito <img src="static/img/down.png"></a></li>
        <li><a href="index.html">Kirjaudu Ulos</a></li>
      </ul>
    </nav>
    
    </div>


    <div class="content info-box">
      <h2>XXXX matkapäiväkirja</h2>
      <div class="info-box">
        <a href="add_report.html"><img class="add" src="static/img/add_flight.png"></a>
        <table>
          <tr>
            <th>Lento
            <th>Pvm
            <th>Päällikkö
            <th>Perämies
            <th>Tyyppi
            <th>Lähtökenttä
            <th>Laskukenttä
            <th>Henkilömäärä
            <th>Laskujen määrä
            <th>Lähtöaika
            <th>Laskuaika
            <th>Lentoaika
            <th>Off-block
            <th>On-block
            <th>Pukkiaika
            <th>Kokonaisaika
            <th>Laskun saaja
            <th>Selite
            <th>Bensa
            <th>Öljy
            <th>Hinta
            <th>Lasku
            <th>Opettajakorvaus
          </tr>
          <tr>
            <td>9724
            <td>18.9.2016
            <td>
            <td>
            <td>HAR
            <td>EFJY
            <td>EFVR
            <td>1
            <td>1
            <td>11:25
            <td>12:05
            <td>40
            <td>11:20
            <td>12:15
            <td>55
            <td>0023:51
            <td>
            <td>
            <td>35
            <td>0
            <td>100
            <td>156234
            <td>ei
          </tr>
          <tr>
            <td>9723
            <td>17.9.2016
            <td>
            <td>
            <td>HAR
            <td>EFVR
            <td>EFJY
            <td>1
            <td>1
            <td>11:25
            <td>12:05
            <td>40
            <td>11:20
            <td>12:15
            <td>55
            <td>0023:51
            <td>
            <td>
            <td>35
            <td>0
            <td>100
            <td>156234
            <td>ei
          </tr>
          <tr>
            <td>9722
            <td>16.9.2016
            <td>
            <td>
            <td>KOU
            <td>EFJY
            <td>EFVR
            <td>1
            <td>1
            <td>11:25
            <td>12:05
            <td>40
            <td>11:20
            <td>12:15
            <td>55
            <td>0023:51
            <td>
            <td>
            <td>35
            <td>0
            <td>100
            <td>156234
            <td>ei
          </tr>
          <tr>
            <td>9721
            <td>13.9.2016
            <td>
            <td>
            <td>HAR
            <td>EFJY
            <td>EFJY
            <td>1
            <td>1
            <td>11:25
            <td>12:05
            <td>40
            <td>11:20
            <td>12:15
            <td>55
            <td>0023:51
            <td>
            <td>
            <td>35
            <td>0
            <td>100
            <td>156234
            <td>ei
          </tr>
          <tr>
            <td>9720
            <td>18.8.2016
            <td>
            <td>
            <td>HAR
            <td>EFJY
            <td>EFJY
            <td>1
            <td>1
            <td>11:25
            <td>12:05
            <td>40
            <td>11:20
            <td>12:15
            <td>55
            <td>0023:51
            <td>
            <td>
            <td>35
            <td>0
            <td>100
            <td>156234
            <td>ei
          </tr>
          <tr>
            <td>9719
            <td>10.7.2016
            <td>
            <td>
            <td>HAR
            <td>EFJY
            <td>EFVR
            <td>1
            <td>1
            <td>11:25
            <td>12:05
            <td>40
            <td>11:20
            <td>12:15
            <td>55
            <td>0023:51
            <td>
            <td>
            <td>35
            <td>0
            <td>100
            <td>156234
            <td>ei
          </tr>
          <tr>
            <td>9718
            <td>6.6.2016
            <td>
            <td>
            <td>KOU
            <td>EFJY
            <td>EFVR
            <td>1
            <td>1
            <td>09:34
            <td>09:06
            <td>40
            <td>11:20
            <td>12:15
            <td>55
            <td>0023:51
            <td>
            <td>
            <td>35
            <td>0
            <td>100
            <td>156234
            <td>ei
          </tr>
          <tr>
            <td>9717
            <td>28.3.2016
            <td>
            <td>
            <td>HAR
            <td>EFJY
            <td>EFVR
            <td>1
            <td>1
            <td>11:25
            <td>12:05
            <td>40
            <td>11:20
            <td>12:15
            <td>55
            <td>0023:51
            <td>
            <td>
            <td>35
            <td>0
            <td>100
            <td>156234
            <td>ei
          </tr>
          <tr>
            <td>9716
            <td>28.1.2016
            <td>
            <td>
            <td>HAR
            <td>EFJY
            <td>EFVR
            <td>1
            <td>1
            <td>11:25
            <td>12:05
            <td>40
            <td>11:20
            <td>12:15
            <td>55
            <td>0023:51
            <td>
            <td>
            <td>35
            <td>0
            <td>100
            <td>156234
            <td>ei
          </tr>
          <tr>
            <td>9715
            <td>8.1.2016
            <td>
            <td>
            <td>HAR
            <td>EFJY
            <td>EFVR
            <td>1
            <td>1
            <td>11:25
            <td>12:05
            <td>40
            <td>11:20
            <td>12:15
            <td>55
            <td>0023:51
            <td>
            <td>
            <td>35
            <td>0
            <td>100
            <td>156234
            <td>ei
          </tr>
        </table>
        
      </div>
    </div>

  </div>


  <script>
  </script>
</body>
</html>
